### PR TITLE
Fix for new gstatic libraries

### PR DESCRIPTION
**Pull request by boltex**
Changed the url to the latest 'gstatic' version.
Changed the 'load' and 'callback' calls to match this new version usage.

Fixed the sample app to have tables and annotations work.

Incremented the version to 0.1.1
**This is my first contribution to a github project with the 'pull' mechanic so sorry if I goofed**

### CODE REVIEW

**Comment by nbering** [comment]
My apologies, I want to integrate this feature, but haven't had a change to take a look and test your code because of a recent family emergency. I'm putting it on my calendar for the weekend. Thanks for the pull request.

**Comment by todpunk** [comment]
Two things of note:

First, the version should not always be "current" but should translate a "1.1" passed in into "current" and I'm not sure if there is other string-based versions, like alpha or beta.  This should also **not** modify any numeric string pass-in that isn't "1", "1.0", or "1.1" since Fixed Versions are a thing now.

Second, this will break any users of GeoChart and Map Chart, who must use the old jsapi loader.  I'm not sure how would be best to handle that.  The version change may be enough, but a console warning or something when loading such a chart may be helpful.  See the bottom paragraph of this section: https://developers.google.com/chart/interactive/docs/basic_load_libs#basic-library-loading

**Comment by nbering** [comment]
Looks like they have two named versions. `current` and `upcoming`. I have to stop thinking about charts for now to do paid work. If anyone else wants to give feedback on the pull request, I welcome the help. The main thing is I don't want library loading from the new endpoint to break people who were manually setting the chart options. I plan to deprecate the current mechanism (setting a value in DI) for setting options in favour of a more comprehensive provider with helpful methods, but we're not there, yet.

**Comment by cjeffers** [comment]
Yeah, it seems like there should be a config options to choose the gstatic loader, along with options for it. Working on a PR to that effect

**Comment by nbering** [comment]
Superceded by #310.

**Pull request closed without merging**
