### PR TITLE
function setupAndDraw

### PR DESCRIPTION
**Pull request by yiting007**
When rendering line charts, I got error "Cannot read property 'requiresHtml' of undefined"
Added a check before checking property requiresHtml

### CODE REVIEW

**Comment by Balrog30** [comment]
You're treating the symptom, not the cause.  requiresHtml is a property of the applyFormat's return object.  If requiresHtml is undefined then something went wrong.  I'll take a look later tonight, but more info on the conditions when you got the error would be useful (did you have any formatters defined? was there data assigned to your chart? etc).

**Comment by yiting007** [comment]
Thanks for the reply. Currently I'm using 'formatter': {}. 

You are right this is the symptom only, I'm not sure what the cause is neither. My code was working fine a couple of days ago and without any changes it suddenly doesn't work :(

My code (line chart, old version):
```javascript
    UsageLineChartHits.prototype.drawChart = function (chartObj) {
      chartObj['data'] = this.getLineChart();
      chartObj['options'] = {
        'title': this.title + ' Report Hits'
      };
    };

```
Current version, works with adding "formatters" attribute:
```javascript
chartObj['formatters'] = {};
```

table chart:
```javascript
UsageTableChart.prototype.drawChart = function (chartObj) {
      chartObj['data'] = this.getTableChart();
      chartObj['displayed'] = true;
      chartObj['options'] = {
        'title': this.title + ' Table Chart',
        'isStacked': true,
        'fill': 20,
        'displayExactValues': true,
        'vAxis': {
          'gridlines': {
            'count': 10
          }
        },
        'page': 'enable',
        'pageSize': 20
      };
      chartObj['formatters'] = {};
    };
```
My table chart does not work with setting formatter to {}. It throws the undefined error.

Thanks!

**Comment by Balrog30** [comment]
I feel like I've solved this and didn't merge the fix from my own repo.  Might be wrong, but I'm starting work on it right now.  I'll know more soon.

**Comment by Balrog30** [comment]
There's no other errors?

```JavaScript
chartObj['data'] = this.getTableChart();
```

What is getTableChart returning?  Is it something that can be resolved to a `google.visualization.DataTable()`?

All branches of `FormatManager.applyFormat()` should resolve to an object with a requiresHtml property, which suggests that an error is being thrown somewhere to prevent a proper return from the function.

**Comment by yiting007** [comment]
There is no other error.

The exact error I got is:
```
TypeError: Cannot read property 'requiresHtml' of undefined
    at setupAndDraw (ng-google-chart.js:292)
    at angular.mw.js:16380
    at completeOutstandingRequest (angular.mw.js:4940)
    at angular.mw.js:5328
    (anonymous function) @ angular.mw.js:11699
    $get @ angular.mw.js:8628
    (anonymous function) @ angular.mw.js:16383
    completeOutstandingRequest @ angular.mw.js:4940
    (anonymous function) @ angular.mw.js:5328
```

Actually I got this error before function getTableChart() executed. I checked my backend handlers (the ones I get data from) and they are working fine. I'm still working on it to see where the problem is.

Also I have upload my js file and the output here: https://github.com/yiting007/usage.js 

Thanks!

**Comment by Balrog30** [comment]
I figured it out!  This is going to seem silly, but with the new build system I've been avoiding putting the built ng-google-chart.js just because it's more like 'generated' content than actual changes.

The problem is fixed, I just need to commit the built file.

**Comment by Balrog30** [comment]
Underlying issue should be fixed as of 0787bd3870b6babb3ddc96357e781dd1b7786b63.  By the way, ng-google-chart.js is now the result of a build process.  The actual source to be changed is in a variety of files in `src/`.

Let me know if this fixed the issue for you.

**Comment by yiting007** [comment]
Yes my code works. Thank you!

**Comment by Balrog30** [comment]
I'm glad that fixed it for you.

**Pull request closed without merging**
