### PR TITLE
missing googlechart dependancy added to examples generic.js

### PR DESCRIPTION
**Pull request by d-schmidt**
without this the charts don't work

### CODE REVIEW

**Comment by Balrog30** [comment]
That's because the module is declared in `sample.js`. It's not missing a dependency, you must be loading in a different page and missing the module declaration?

**Comment by d-schmidt** [comment]
If you open this page:
https://angular-google-chart.github.io/angular-google-chart/#/generic/ColumnChart

there is a text box where it is missing. The samples itself are owrking on github.io but if you copy the text shown there they no longer work.

**Comment by Balrog30** [comment]
That's an interesting take on it.  I did think of this but it was just a passing thought.  The samples are more to illustrate how to set up a chart object in a controller, not how to add a module as a dependency.  But declaring a module twice in an application usually causes errors, so I don't believe this will work as it is written.

I don't think it's a terribly bad idea to add a module declaration to the documentation somewhere, but I find myself looking at code files to find module declarations for almost every module I've used.  So, I don't think it's even that uncommon for the module name to be  undocumented.

This is certainly something to consider for a future version of the documentation pages, which could certainly use a major overhaul in how it's handled (committed bugs really shouldn't break the documentation).

If you feel it's not clear how to add the module, I think it would probably be best just to add something to `readme.md` after "Install with Bower".  If you want to submit another pull request to that effect I will be happy to merge it in.

**Comment by d-schmidt** [comment]
Okay I get your point and why changing the generic.js is not the best solution.
> The samples are more to illustrate how to set up a chart object in a controller

This is true for this example: https://angular-google-chart.github.io/angular-google-chart/#/fat
There is just the chart object.    
But as someone currently learning angularjs it was quite confusing and took me some time to figure out why even the copied bar chart example isn't working. I only noticed the missing piece when I checked the `plnkr.co` examples for like the 5th time.

**Pull request closed without merging**
