### PR TITLE
Add config options for gstatic loading

### PR DESCRIPTION
**Pull request by cjeffers**
As per https://github.com/angular-google-chart/angular-google-chart/pull/268 , load using new gstatic libraries. To maintain backwards compatibility, the default (JSAPI) loading is used. If the gstatic loading is desired, can be enabled e.g.

```
angular
    .module('sample', ['googlechart']);

angular
    .module('googlechart')
    .value('googleChartApiConfig', {
        useGstaticLoader: true,
        gstaticLoaderVersion: '44',
        optionalSettings: {
            packages: [ 'corechart' ]
        }
    });
```

Other changes:
- Changed tests to use Chrome, because PhantomJS really did not like loading using the google.charts.load API.
- Changed structure of googleChartApiPromise spec, because directly calling $get resulted in an error when it had dependencies.
- Tests included.

Issues:
- This is simply expanding on using a `value` as the configuration object, which means that when configuring, all the required options must be present, or errors will happen. This is not a result of the new options, it's just because overwriting a `value` overwrites the whole thing. Thoughts on other ways to handle configuration? Providers?
- As @todpunk [mentioned](https://github.com/angular-google-chart/angular-google-chart/pull/268#issuecomment-208519790) on #268, this doesn't account for Geo or MapCharts. I think it should be possible to check for their presence in `optionalSettings` and add both required `<script>` elements to the DOM.

### CODE REVIEW

**Comment by nbering** [comment]
Can you elaborate on the PhantomJS issue? I was using Phantom because I sometimes develop on http://c9.io so that I can move between machines easily. Not a hard requirement, and I haven't had much time for the project at all lately, but I'm curious what the problem was.

**Comment by cjeffers** [comment]
Yeah, the issue I found was described (but not solved) in [this google group discussion](https://groups.google.com/forum/#!msg/google-visualization-api/hBCwxtXYNZ8/IkpXeqM7FwAJ), beginning with [this comment](https://groups.google.com/d/msg/google-visualization-api/hBCwxtXYNZ8/b-a9NPzGEQAJ). Kevin Crawley's posts are the ones describing the issue, which I seemed to be having in PhantomJS as well. It seems like they still haven't come to a solution regarding PhantomJS and the new charts loader.

The old loader specs passed fine, but the specs for the new gstatic loader would never get to the callback. I hardcoded in the [exact syntax from the Google Charts API docs](https://developers.google.com/chart/interactive/docs/basic_load_libs#update-library-loader-code), with a stupid-simple callback to make sure it wasn't some logical error. The callback was still never called.

Once I changed karma to use Chrome, the callback was registered/called correctly, and I was able to make all the tests pass. I've had trouble with PhantomJS inconsistencies on other projects, and have unfortunately started to be leery of it when doing anything very complex.

Keeping PhantomJS would be nice for exactly the reasons you're describing, but I think we'd have to leave the new loader code itself untested. We could mock/stub/fake to make sure the loader API is called correctly, but I don't think we can test it directly. I could amend the PR to that effect?

--

On another note, any thoughts on ways to make a more robust configuration?

**Comment by nbering** [comment]
Ok, I pulled this down, built and tested out briefly with one of the demo apps. The first thing I found with the `useGstaticLoader: true` parameter is a little awkward, but changing that did work. The bigger issue I had with this API is requiring `gstaticLoaderVersion`. If they set `useGstaticLoader`, I think we can just use the value they put in for `version`. Also, if you omit the value it tries to load from `https://www.gstatic.com/charts/undefined/loader.js`.

It's probably best if the settings used a simpler name like `useNewLoader`. The capitalization of that name alone makes it something I'd have to look up all the time. And use just `version` or at least a smart default for the extra version setting. That way we can let early adopters migrate to the new loader, and then drop the value from settings altogether in a few months so that everyone is using gstatic as the Google team would prefer that we do anyway. I'm pretty sure the APIs are compatible from an AGC public-API standpoint, it's just using a different endpoint and different javascript namespace for the loader.

**Comment by cjeffers** [comment]
I agree, the `useGstatic...` name was not easy to remember. I changed the config option to `useNewLoader`, and put the versioning logic behind a separate factory, `newLoaderVersion`. Thoughts? Would it be better to throw some error rather than silently defaulting to `'current'` for the version? Also, I didn't update the changelog or version because I'm not certain how you maintain those.

**Comment by nbering** [comment]
I'll look at your changes soon.

### Process

I add things to the `unreleased` version in change log as they make it into the development branch. Topics are added, changed, removed. Fixed might also be suitable in some cases.

Once development is has had some new features and I'm pretty sure they're stable I'll tag a new version. If the changes are big I would use a beta prerelease tag first to make sure people's package loaders aren't defaulting them to a slightly unstable poorly tested build.  Hit tags automatically get pulled by ce js.

Along with the git tag, package files get bumped, and I merge into master branch. Documentation gets release notes added as a Jekyll post, and I copy all the docs into another version-tagged directory, update pointers to `latest` and add whatever new features were in the change log.  Docs sight has to wait for cdnjs to catch up because it pulls the JavaScript from there so that all the examples can run on the site in the version that they document without having a folder with every version in it in source control.

**Comment by nbering** [comment]
Oh right, also change log gets added to the tag in GitHub releases section, and code gets built with minification but without source maps.

**Comment by zombeej** [comment]
Hello,
I was wondering if this PR is going to be merged anytime soon?

**Comment by nbering** [comment]
Superceded by #310.

**Pull request closed without merging**
