### PR TITLE
Swappable Library Loader Strategies

### PR DESCRIPTION
**Pull request by nbering**
Related to: #305, #283, #267, #252, #238

This needs more documentation, but here's the idea:

```js
angular.module('myapp', ['googlechart'])
  .config(function(agcLibraryLoaderProvider){
    // options: 'jsapi', 'gstatic', 'null' (not the value, the string 'null').
    agcLibraryLoaderProvider.setLoader("gstatic");
  })
  .config(function(agcGstaticLoaderProvider){
    agcGstaticLoaderProvider.setVersion('current'); //this is the default
    agcGstaticLoaderProvider.addPackage('map');
    agcGstaticLoaderProvider.setOption('mapsApiKey', '===YOUR KEY HERE===');
  });
```

The old JSAPI endpoint is still the default to avoid making this a breaking change. Will update this later.

There's also a "null" loader type if you're loading the charts library yourself. If you get the trigger function from the null loader's provider, it will wait for you to call that trigger function before resolving the chartsApiPromise. This might help with #283 in particular.

Loaders a grabbed using the injector, so you could create a provider like `agcFooLoader`, and set the loader to `"foo"`, and it would use your loader. Such a provider should return an angular `$q` promise that resolves with the google charts library (ie. `window.google`). `agcNullLoader` should handle the majority of edge cases.

I committed the build, so if anyone wants to test this (@aidaeology?), I'd love the feedback.

Apologies for the long-time coming on this. Wanted to do it right, which - of course - just leads to procrastination.

### CODE REVIEW

**Comment by nbering** [comment]
Staged some documentation changes for this PR on https://github.com/nbering/angular-google-chart/tree/docs-site.

Preparing this and some other changes to be made as 1.0.0-beta.1 release. Will be trimming some other historical weirdness and switching over to the gstatic API at the same time. Will provide updates about other changes in their own issues/pull requests after this one.

**Comment by charlieanstey** [comment]
I couldn't find any documentation in the repo for specifying an API key.

So having tested your snippet above, the second config works when injecting ```agcGstaticLoaderProvider``` - not ```agcGstaticLoader```

**Comment by nbering** [comment]
@charlieanstey Good catch on Provider name. I rushed through that PR description a bit and didn't test what I wrote.

I'm not sure what you're referencing with the API Key. What I've added is support for passing any additional configuration parameter to google's loader mechanism. This was primarily to support the maps API key as I've demonstrated in the PR description and in the docs for the [agcGstaticLoaderProvider](http://angular-google-chart.github.io/angular-google-chart/docs/1.0.0-beta.1/providers/agcGstaticLoader/).

Was there something else I needed to document about that?

**Comment by charlieanstey** [comment]
No worries!

API key-wise, this PR was the only place I found an example of setting the API key.

Suffice it to say, I obviously couldn't read yesterday - that's my bad. Seen your example now at the link. Cheers for that

**Pull request merged**
